String refereeAssetSlug(String name) {
  final lower = name.toLowerCase().trim();
  final normalized = lower.replaceAll('&', 'and').replaceAll("'", '');
  final collapsed = normalized.replaceAll(RegExp(r'[^a-z0-9]+'), '_');
  final trimmed = collapsed.replaceAll(RegExp(r'^_+|_+$'), '');
  return trimmed.isEmpty ? 'unknown_official' : trimmed;
}

const Map<String, String> _refereeAssetLookup = {
  'aaron_smith': 'assets/referees/Aaron Smith.jpg',
  'andy_nagy': 'assets/referees/Andy Nagy.jpg',
  'ashley_moyer_gleich': 'assets/referees/Ashley Moyer-Gleich.jpg',
  'ben_taylor': 'assets/referees/Ben Taylor.jpg',
  'bennie_adams': 'assets/referees/Bennie Adams.jpg',
  'bill_kennedy': 'assets/referees/Bill Kennedy.jpg',
  'biniam_maru': 'assets/referees/Biniam Maru.jpg',
  'brandon_adair': 'assets/referees/Brandon Adair.jpg',
  'brandon_schwab': 'assets/referees/Brandon Schwab.jpg',
  'brent_barnaky': 'assets/referees/Brent Barnaky.jpg',
  'brent_haskill': 'assets/referees/Brent Haskill.jpg',
  'brett_nansel': 'assets/referees/Brett Nansel.jpg',
  'brian_forte': 'assets/referees/Brian Forte.jpg',
  'che_flores': 'assets/referees/Che Flores.jpeg',
  'cj_washington': 'assets/referees/CJ Washington.jpeg',
  'clare_aubry': 'assets/referees/Clare Aubry.jpg',
  'courtney_kirkland': 'assets/referees/Courtney Kirkland.jpg',
  'curtis_blair': 'assets/referees/Curtis Blair.jpg',
  'danielle_scott': 'assets/referees/Danielle Scott.jpg',
  'dannica_baroody': 'assets/referees/Dannica Baroody.jpg',
  'dannica_mosher': 'assets/referees/Dannica Mosher.jpg',
  'david_guthrie': 'assets/referees/David Guthrie.jpg',
  'dedric_taylor': 'assets/referees/Dedric Taylor.jpg',
  'derek_richardson': 'assets/referees/Derek Richardson.jpg',
  'derrick_collins': 'assets/referees/Derrick Collins.jpg',
  'ed_malloy': 'assets/referees/Ed Malloy.jpg',
  'eric_dalen': 'assets/referees/Eric Dalen.jpg',
  'evan_scott': 'assets/referees/Evan Scott.jpg',
  'gediminas_petraitis': 'assets/referees/Gediminas Petraitis.jpg',
  'intae_hwang': 'assets/referees/Intae Hwang.jpg',
  'j_t_orr': 'assets/referees/JT Orr.jpg',
  'jacyn_goble': 'assets/referees/Jacyn Goble.jpg',
  'james_capers': 'assets/referees/James Capers.jpg',
  'james_williams': 'assets/referees/James Williams.jpg',
  'jason_goldenberg': 'assets/referees/Jason Goldenberg.jpg',
  'jb_derosa': 'assets/referees/JB DeRosa.jpg',
  'jd_ralls': 'assets/referees/JD Ralls.jpg',
  'jenna_reneau': 'assets/referees/Jenna Reneau.jpg',
  'jenna_schroeder': 'assets/referees/Jenna Schroeder.jpg',
  'john_butler': 'assets/referees/John Butler.jpg',
  'john_conley': 'assets/referees/John Conley.jpg',
  'john_goble': 'assets/referees/John Goble.jpg',
  'jonathan_sterling': 'assets/referees/Jonathan Sterling.jpg',
  'josh_tiven': 'assets/referees/Josh Tiven.jpg',
  'justin_van_duyne': 'assets/referees/Justin Van Duyne.jpg',
  'karl_lane': 'assets/referees/Karl Lane.jpg',
  'kevin_cutler': 'assets/referees/Kevin Cutler.jpg',
  'kevin_scott': 'assets/referees/Kevin Scott.jpg',
  'lauren_holtkamp_sterling': 'assets/referees/Lauren Holtkamp-Sterling.jpg',
  'leon_wood': 'assets/referees/Leon Wood.jpg',
  'leaon_wood': 'assets/referees/Leon Wood.jpg',
  'marat_kogut': 'assets/referees/Marat Kogut.jpg',
  'marc_davis': 'assets/referees/Marc Davis.jpg',
  'mark_lindsay': 'assets/referees/Mark Lindsay.jpg',
  'matt_boland': 'assets/referees/Matt Boland.jpeg',
  'matt_kallio': 'assets/referees/Matt Kallio.jpg',
  'matt_myers': 'assets/referees/Matt Myers.jpg',
  'michael_smith': 'assets/referees/Michael Smith.jpg',
  'mitchell_ervin': 'assets/referees/Mitchell Ervin.jpg',
  'mousa_dagher': 'assets/referees/Mousa Dagher.jpg',
  'natalie_sago': 'assets/referees/Natalie Sago.jpg',
  'nate_green': 'assets/referees/Nate Green.jpg',
  'nick_buchert': 'assets/referees/Nick Buchert.jpg',
  'pat_fraher': 'assets/referees/Pat Fraher.jpg',
  'pat_oconnell': 'assets/referees/Pat O\'Connell.jpg',
  'phenizee_ransom': 'assets/referees/Phenizee Ransom.jpg',
  'phemizee_ransom': 'assets/referees/Phenizee Ransom.jpg',
  'ray_acosta': 'assets/referees/Ray Acosta.jpg',
  'robert_hussey': 'assets/referees/Robert Hussey.jpg',
  'rodney_mott': 'assets/referees/Rodney Mott.jpg',
  'scott_foster': 'assets/referees/Scott Foster.jpg',
  'scott_twardoski': 'assets/referees/Scott Twardoski.jpg',
  'scott_wall': 'assets/referees/Scott Wall.jpeg',
  'sean_corbin': 'assets/referees/Sean Corbin.jpeg',
  'sean_wright': 'assets/referees/Sean Wright.jpg',
  'sharae_mitchell': 'assets/referees/Sha\'Rae Mitchell.jpg',
  'simone_jelks': 'assets/referees/Simone Jelks.jpg',
  'suyash_mehta': 'assets/referees/Suyash Mehta.jpg',
  'tom_washington': 'assets/referees/Tom Washington.jpg',
  'tony_brothers': 'assets/referees/Tony Brothers.jpg',
  'tre_maddox': 'assets/referees/Tre Maddox.jpg',
  'tyler_ford': 'assets/referees/Tyler Ford.jpg',
  'tyler_mirkovich': 'assets/referees/Tyler Mirkovich.jpg',
  'tyler_ricks': 'assets/referees/Tyler Ricks.jpg',
  'zach_zarba': 'assets/referees/Zach Zarba.jpg',
};

String refereeAssetPath(String name, {String extension = 'jpg'}) {
  final slug = refereeAssetSlug(name);
  return _refereeAssetLookup[slug] ?? 'assets/referees/$slug.$extension';
}
